---
- name: Create app container
  docker_container:
    name: "{{application_name}}"
    image: "namelivia/{{application_name}}:latest"
    memory: "200MB"
    pull: true
    restart_policy: "always"
    log_driver: "awslogs"
    log_options:
        awslogs-region: "{{cloudwatch_region}}"
        awslogs-group: "{{cloudwatch_log_group}}"
        awslogs-stream: "{{application_name}}"
    networks:
      - name: "pomerium"
    exposed_ports:
      - "80"
    env:
      TELEGRAM_API_ID: "{{notifications_telegram_api_id}}"
      TELEGRAM_CHAT_ID: "{{notifications_telegram_chat_id}}"

